// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.Delivery;
import com.roo.team01.domain.DeliveryIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DeliveryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DeliveryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DeliveryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DeliveryIntegrationTest: @Transactional;
    
  
   /* 
    @Test
    public void DeliveryIntegrationTest.testCountDeliverys() {
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", dod.getRandomDelivery());
        long count = Delivery.countDeliverys();
        Assert.assertTrue("Counter for 'Delivery' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DeliveryIntegrationTest.testFindDelivery() {
        Delivery obj = dod.getRandomDelivery();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to provide an identifier", id);
        obj = Delivery.findDelivery(id);
        Assert.assertNotNull("Find method for 'Delivery' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Delivery' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DeliveryIntegrationTest.testFindAllDeliverys() {
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", dod.getRandomDelivery());
        long count = Delivery.countDeliverys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Delivery', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Delivery> result = Delivery.findAllDeliverys();
        Assert.assertNotNull("Find all method for 'Delivery' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Delivery' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DeliveryIntegrationTest.testFindDeliveryEntries() {
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", dod.getRandomDelivery());
        long count = Delivery.countDeliverys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Delivery> result = Delivery.findDeliveryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Delivery' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Delivery' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DeliveryIntegrationTest.testFlush() {
        Delivery obj = dod.getRandomDelivery();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to provide an identifier", id);
        obj = Delivery.findDelivery(id);
        Assert.assertNotNull("Find method for 'Delivery' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDelivery(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Delivery' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeliveryIntegrationTest.testMergeUpdate() {
        Delivery obj = dod.getRandomDelivery();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to provide an identifier", id);
        obj = Delivery.findDelivery(id);
        boolean modified =  dod.modifyDelivery(obj);
        Integer currentVersion = obj.getVersion();
        Delivery merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Delivery' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DeliveryIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", dod.getRandomDelivery());
        Delivery obj = dod.getNewTransientDelivery(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Delivery' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Delivery' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Delivery' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DeliveryIntegrationTest.testRemove() {
        Delivery obj = dod.getRandomDelivery();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Delivery' failed to provide an identifier", id);
        obj = Delivery.findDelivery(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Delivery' with identifier '" + id + "'", Delivery.findDelivery(id));
    }*/
    
}
