// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.LogUser;
import com.roo.team01.domain.LogUserIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LogUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LogUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LogUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LogUserIntegrationTest: @Transactional;
    
    
   /* @Test
    public void LogUserIntegrationTest.testCountLogUsers() {
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", dod.getRandomLogUser());
        long count = LogUser.countLogUsers();
        Assert.assertTrue("Counter for 'LogUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LogUserIntegrationTest.testFindLogUser() {
        LogUser obj = dod.getRandomLogUser();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to provide an identifier", id);
        obj = LogUser.findLogUser(id);
        Assert.assertNotNull("Find method for 'LogUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LogUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LogUserIntegrationTest.testFindAllLogUsers() {
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", dod.getRandomLogUser());
        long count = LogUser.countLogUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'LogUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LogUser> result = LogUser.findAllLogUsers();
        Assert.assertNotNull("Find all method for 'LogUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LogUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LogUserIntegrationTest.testFindLogUserEntries() {
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", dod.getRandomLogUser());
        long count = LogUser.countLogUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LogUser> result = LogUser.findLogUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LogUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LogUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LogUserIntegrationTest.testFlush() {
        LogUser obj = dod.getRandomLogUser();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to provide an identifier", id);
        obj = LogUser.findLogUser(id);
        Assert.assertNotNull("Find method for 'LogUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLogUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LogUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LogUserIntegrationTest.testMergeUpdate() {
        LogUser obj = dod.getRandomLogUser();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to provide an identifier", id);
        obj = LogUser.findLogUser(id);
        boolean modified =  dod.modifyLogUser(obj);
        Integer currentVersion = obj.getVersion();
        LogUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LogUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LogUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", dod.getRandomLogUser());
        LogUser obj = dod.getNewTransientLogUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LogUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LogUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LogUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LogUserIntegrationTest.testRemove() {
        LogUser obj = dod.getRandomLogUser();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LogUser' failed to provide an identifier", id);
        obj = LogUser.findLogUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LogUser' with identifier '" + id + "'", LogUser.findLogUser(id));
    }*/
    
}
