// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.LogUserIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LogUserIntegrationTest_Roo_Configurable {
    
    declare @type: LogUserIntegrationTest: @Configurable;
    
}
