// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.PreOrder;
import com.roo.team01.domain.PreOrderIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PreOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PreOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PreOrderIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PreOrderIntegrationTest: @Transactional;
    
  /*  
    @Test
    public void PreOrderIntegrationTest.testCountPreOrders() {
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", dod.getRandomPreOrder());
        long count = PreOrder.countPreOrders();
        Assert.assertTrue("Counter for 'PreOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PreOrderIntegrationTest.testFindPreOrder() {
        PreOrder obj = dod.getRandomPreOrder();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to provide an identifier", id);
        obj = PreOrder.findPreOrder(id);
        Assert.assertNotNull("Find method for 'PreOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PreOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PreOrderIntegrationTest.testFindAllPreOrders() {
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", dod.getRandomPreOrder());
        long count = PreOrder.countPreOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'PreOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PreOrder> result = PreOrder.findAllPreOrders();
        Assert.assertNotNull("Find all method for 'PreOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PreOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PreOrderIntegrationTest.testFindPreOrderEntries() {
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", dod.getRandomPreOrder());
        long count = PreOrder.countPreOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PreOrder> result = PreOrder.findPreOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PreOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PreOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PreOrderIntegrationTest.testFlush() {
        PreOrder obj = dod.getRandomPreOrder();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to provide an identifier", id);
        obj = PreOrder.findPreOrder(id);
        Assert.assertNotNull("Find method for 'PreOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPreOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PreOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PreOrderIntegrationTest.testMergeUpdate() {
        PreOrder obj = dod.getRandomPreOrder();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to provide an identifier", id);
        obj = PreOrder.findPreOrder(id);
        boolean modified =  dod.modifyPreOrder(obj);
        Integer currentVersion = obj.getVersion();
        PreOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PreOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PreOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", dod.getRandomPreOrder());
        PreOrder obj = dod.getNewTransientPreOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PreOrder' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PreOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PreOrderIntegrationTest.testRemove() {
        PreOrder obj = dod.getRandomPreOrder();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PreOrder' failed to provide an identifier", id);
        obj = PreOrder.findPreOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PreOrder' with identifier '" + id + "'", PreOrder.findPreOrder(id));
    }*/
    
}
