// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.Promotion;
import com.roo.team01.domain.PromotionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PromotionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PromotionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PromotionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PromotionIntegrationTest: @Transactional;
    
    
    /*
    @Test
    public void PromotionIntegrationTest.testCountPromotions() {
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", dod.getRandomPromotion());
        long count = Promotion.countPromotions();
        Assert.assertTrue("Counter for 'Promotion' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PromotionIntegrationTest.testFindPromotion() {
        Promotion obj = dod.getRandomPromotion();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to provide an identifier", id);
        obj = Promotion.findPromotion(id);
        Assert.assertNotNull("Find method for 'Promotion' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Promotion' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PromotionIntegrationTest.testFindAllPromotions() {
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", dod.getRandomPromotion());
        long count = Promotion.countPromotions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Promotion', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Promotion> result = Promotion.findAllPromotions();
        Assert.assertNotNull("Find all method for 'Promotion' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Promotion' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PromotionIntegrationTest.testFindPromotionEntries() {
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", dod.getRandomPromotion());
        long count = Promotion.countPromotions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Promotion> result = Promotion.findPromotionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Promotion' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Promotion' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PromotionIntegrationTest.testFlush() {
        Promotion obj = dod.getRandomPromotion();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to provide an identifier", id);
        obj = Promotion.findPromotion(id);
        Assert.assertNotNull("Find method for 'Promotion' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPromotion(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Promotion' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PromotionIntegrationTest.testMergeUpdate() {
        Promotion obj = dod.getRandomPromotion();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to provide an identifier", id);
        obj = Promotion.findPromotion(id);
        boolean modified =  dod.modifyPromotion(obj);
        Integer currentVersion = obj.getVersion();
        Promotion merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Promotion' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PromotionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", dod.getRandomPromotion());
        Promotion obj = dod.getNewTransientPromotion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Promotion' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Promotion' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Promotion' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PromotionIntegrationTest.testRemove() {
        Promotion obj = dod.getRandomPromotion();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promotion' failed to provide an identifier", id);
        obj = Promotion.findPromotion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Promotion' with identifier '" + id + "'", Promotion.findPromotion(id));
    }*/
    
}
