// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.Stock_billIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Stock_billIntegrationTest_Roo_Configurable {
    
    declare @type: Stock_billIntegrationTest: @Configurable;
    
}
