// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.Stock_bill;
import com.roo.team01.domain.Stock_billIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Stock_billIntegrationTest_Roo_IntegrationTest {
    
    declare @type: Stock_billIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: Stock_billIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: Stock_billIntegrationTest: @Transactional;
    
    
    
    /*@Test
    public void Stock_billIntegrationTest.testCountStock_bills() {
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", dod.getRandomStock_bill());
        long count = Stock_bill.countStock_bills();
        Assert.assertTrue("Counter for 'Stock_bill' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void Stock_billIntegrationTest.testFindStock_bill() {
        Stock_bill obj = dod.getRandomStock_bill();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to provide an identifier", id);
        obj = Stock_bill.findStock_bill(id);
        Assert.assertNotNull("Find method for 'Stock_bill' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Stock_bill' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void Stock_billIntegrationTest.testFindAllStock_bills() {
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", dod.getRandomStock_bill());
        long count = Stock_bill.countStock_bills();
        Assert.assertTrue("Too expensive to perform a find all test for 'Stock_bill', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Stock_bill> result = Stock_bill.findAllStock_bills();
        Assert.assertNotNull("Find all method for 'Stock_bill' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Stock_bill' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void Stock_billIntegrationTest.testFindStock_billEntries() {
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", dod.getRandomStock_bill());
        long count = Stock_bill.countStock_bills();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Stock_bill> result = Stock_bill.findStock_billEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Stock_bill' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Stock_bill' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void Stock_billIntegrationTest.testFlush() {
        Stock_bill obj = dod.getRandomStock_bill();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to provide an identifier", id);
        obj = Stock_bill.findStock_bill(id);
        Assert.assertNotNull("Find method for 'Stock_bill' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStock_bill(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Stock_bill' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Stock_billIntegrationTest.testMergeUpdate() {
        Stock_bill obj = dod.getRandomStock_bill();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to provide an identifier", id);
        obj = Stock_bill.findStock_bill(id);
        boolean modified =  dod.modifyStock_bill(obj);
        Integer currentVersion = obj.getVersion();
        Stock_bill merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Stock_bill' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Stock_billIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", dod.getRandomStock_bill());
        Stock_bill obj = dod.getNewTransientStock_bill(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Stock_bill' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Stock_bill' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void Stock_billIntegrationTest.testRemove() {
        Stock_bill obj = dod.getRandomStock_bill();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stock_bill' failed to provide an identifier", id);
        obj = Stock_bill.findStock_bill(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Stock_bill' with identifier '" + id + "'", Stock_bill.findStock_bill(id));
    }*/
    
}
