// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.Add_Promotion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Add_Promotion_Roo_Configurable {
    
    declare @type: Add_Promotion: @Configurable;
    
}
