// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.team01.domain;

import com.roo.team01.domain.LogUserRole;

privileged aspect LogUserRole_Roo_JavaBean {
    
    public String LogUserRole.getRoleName() {
        return this.roleName;
    }
    
    public void LogUserRole.setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
}
